# Site settings
title: Smiles are mostly quite communicative :)!!
description: Sometimes, somethings are required to be shared.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shruti
user_description: I am a Shruti Sharma, a final year undergraduate student of BITS Pilani, an avid writer, and a future roboticist and hopefully a good teacher.
user_title: Roboticist
email: shruti12101997@gmail.com
#twitter_username: lorem_ipsum
github_username:  shruti1210
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-slate
